parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Clickcars\:
        resource: '../src/'
        exclude:
            - '..src/Domain/Model/'

    Clickcars\Infrastructure\Driver\Presentation\Controllers\:
        resource: '../src/Infrastructure/Driver/Presentation/Controllers/'
        tags: ["controller.service_arguments"]

    Clickcars\Application\:
        resource: '../src/Application/'
        tags: [ "controller.service_arguments" ]

    Clickcars\Application\Driven\Characters:
        class: Clickcars\Application\GetCharacters
    Clickcars\Application\Driven\CharactersProvider:
        class: Clickcars\Infrastructure\Driven\RickAndMortyProvider
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Clickcars\Infrastructure\Listeners\JsonTransformerExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 100 }